const ACTION_TYPE = {
    ADD_FOLDER: 'ADD_FOLDER',
    ADD_TASK: 'ADD_TASK',
    OPEN_FOLDER: 'OPEN_FOLDER',
    CLOSE_FOLDER: 'CLOSE_FOLDER',
    OPEN_TASK: 'OPEN_TASK',
    CLOSE_TASK: 'CLOSE_TASK',
    SELECT_TASK: 'SELECT_TASK',
    SAVE_TASK_TIME: 'SAVE_TASK_TIME',
    ADD_TODAY_TASK: 'ADD_TODAY_TASK',
    DELETE_FOLDER: 'DELETE_FOLDER',
    CHECK_TASK: 'CHECK_TASK',
    DELETE_TASK: 'DELETE_TASK',
    MOVE_TASK: 'MOVE_TASK',
};

export default ACTION_TYPE;